'use client'

import * as React from 'react'
import { useRouter } from 'next/navigation'
import { Button } from '@/components/ui/button'
import {
  InputOTP,
  InputOTPGroup,
  InputOTPSlot,
} from '@/components/ui/input-otp'

export default function MFAPage() {
  const router = useRouter()
  const [value, setValue] = React.useState('')
  const [isVerifying, setIsVerifying] = React.useState(false)

  const handleVerify = () => {
    if (value.length !== 6) return
    
    setIsVerifying(true)
    
    // Simulate verification delay
    setTimeout(() => {
      router.push('/dashboard')
    }, 2000)
  }

  return (
    <div className="min-h-screen w-full bg-background flex items-center justify-center">
      {/* Glassmorphism Card */}
      <div className="w-full max-w-md mx-4">
        <div className="backdrop-blur-md bg-black/50 border border-border rounded-lg p-8 shadow-2xl">
          {/* Header */}
          <div className="text-center mb-8">
            <h1 className="text-xl font-bold font-mono text-success tracking-wider mb-2">
              SECURITY PROTOCOL ALPHA
            </h1>
            <p className="text-sm font-mono text-muted-foreground">
              Enter the 6-digit session token generated by your hardware key.
            </p>
          </div>

          {/* OTP Input */}
          <div className="flex flex-col items-center gap-8">
            <InputOTP
              maxLength={6}
              value={value}
              onChange={(value) => setValue(value)}
              className="gap-2"
            >
              <InputOTPGroup className="gap-2">
                {[0, 1, 2, 3, 4, 5].map((index) => (
                  <InputOTPSlot
                    key={index}
                    index={index}
                    className="size-14 text-xl font-mono font-bold bg-black/30 border border-border rounded-md first:rounded-md last:rounded-md first:border last:border data-[active=true]:border-success data-[active=true]:ring-success/30"
                  />
                ))}
              </InputOTPGroup>
            </InputOTP>

            {/* Verify Button */}
            <Button
              onClick={handleVerify}
              disabled={value.length !== 6 || isVerifying}
              variant="outline"
              className="w-full h-12 bg-transparent border-2 border-foreground text-foreground hover:bg-foreground hover:text-background font-mono font-bold tracking-wider text-sm transition-all disabled:opacity-50"
            >
              {isVerifying ? (
                <span className="flex items-center gap-2">
                  <span className="size-4 border-2 border-foreground/30 border-t-foreground rounded-full animate-spin" />
                  VERIFYING...
                </span>
              ) : (
                'VERIFY & CONNECT'
              )}
            </Button>
          </div>

          {/* Footer */}
          <div className="mt-8 text-center">
            <p className="text-xs font-mono text-muted-foreground">
              Token expires in <span className="text-success">04:59</span>
            </p>
          </div>
        </div>
      </div>
    </div>
  )
}
